# Minimal example with TensorFlow 2.0
In this notebook we will recreate our machine learning algorithm using TF 2.0.

## Import the relevant libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## Data generation

In [2]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size =(observations, 1))
zs = np.random.uniform(-10, 10, (observations, 1))

generated_inputs = np.column_stack((xs,zs))

noise = np.random.uniform(-1, 1, (observations,1))

generated_targets = 2*xs - 3*zs + 5 + noise

Saving Tensor Flow



In [3]:
np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

## Solving with TensorFlow

In [4]:
training_data = np.load('TF_intro.npz')
type(training_data)


numpy.lib.npyio.NpzFile

In [5]:
'''
lst = training_data.files
#print(lst)
for item in lst:
    print(item)
    print(training_data[item])
'''

'\nlst = training_data.files\n#print(lst)\nfor item in lst:\n    print(item)\n    print(training_data[item])\n'

In [6]:
training_data['inputs']

array([[ 9.99868754,  1.66778964],
       [-3.07950596,  6.44413697],
       [-6.86294718,  5.2065046 ],
       ...,
       [-9.24715054,  1.59517631],
       [ 8.49041726, -4.48201166],
       [ 2.92629644,  2.54133295]])

In [7]:
training_data['targets']

array([[ 2.07651350e+01],
       [-1.98316057e+01],
       [-2.40845774e+01],
       [ 4.57371234e+01],
       [-1.17374425e+01],
       [-1.00083343e+01],
       [-1.00194962e+01],
       [ 1.59493586e+01],
       [ 2.87255060e+01],
       [-5.41269994e+00],
       [-1.58225226e+01],
       [ 3.84733374e+01],
       [-1.65176530e+01],
       [ 2.70211401e+01],
       [-1.97287867e+01],
       [ 3.87808175e+01],
       [ 1.75253207e+01],
       [-2.40152109e+01],
       [-3.80412565e+01],
       [ 2.28529977e+01],
       [ 1.34594283e+01],
       [ 2.29837869e+01],
       [ 1.22656560e+01],
       [ 4.12533390e+01],
       [ 2.39530609e+01],
       [-1.90780882e+01],
       [ 1.91142289e+01],
       [-1.21151107e+01],
       [ 3.53013910e+01],
       [ 3.68710975e+00],
       [ 2.82150221e+01],
       [-4.04332267e+01],
       [-2.94679900e+00],
       [ 8.08982710e+00],
       [ 3.97954150e+01],
       [-1.74257110e+00],
       [ 3.83549292e+01],
       [-3.83942044e+00],
       [-8.9

In [9]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([
    #tf.keras.layers.Dense(output_size)  # TF automatically sets weights and biases
    tf.keras.layers.Dense(output_size,
                        # To initialize weight and bias
                         kernel_initializer = tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                         bias_initializer = tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                         ) 
])

#model.compile(optimizer = 'sgd', loss = 'mean_squared_error')

# Adding learning rate
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
model.compile(optimizer = custom_optimizer, loss = 'mean_squared_error')

#model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=0)  # Silent or no output
#model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=1)  # Progress Bar
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)   # One line per epoch

Train on 1000 samples
Epoch 1/100
1000/1000 - 1s - loss: 26.3420
Epoch 2/100
1000/1000 - 0s - loss: 1.2200
Epoch 3/100
1000/1000 - 0s - loss: 0.4334
Epoch 4/100
1000/1000 - 0s - loss: 0.4383
Epoch 5/100
1000/1000 - 0s - loss: 0.3718
Epoch 6/100
1000/1000 - 0s - loss: 0.3933
Epoch 7/100
1000/1000 - 0s - loss: 0.3805
Epoch 8/100
1000/1000 - 0s - loss: 0.3920
Epoch 9/100
1000/1000 - 0s - loss: 0.3950
Epoch 10/100
1000/1000 - 0s - loss: 0.3672
Epoch 11/100
1000/1000 - 0s - loss: 0.3846
Epoch 12/100
1000/1000 - 0s - loss: 0.4417
Epoch 13/100
1000/1000 - 0s - loss: 0.3797
Epoch 14/100
1000/1000 - 0s - loss: 0.3745
Epoch 15/100
1000/1000 - 0s - loss: 0.3471
Epoch 16/100
1000/1000 - 0s - loss: 0.3741
Epoch 17/100
1000/1000 - 0s - loss: 0.3892
Epoch 18/100
1000/1000 - 0s - loss: 0.3857
Epoch 19/100
1000/1000 - 0s - loss: 0.4019
Epoch 20/100
1000/1000 - 0s - loss: 0.3654
Epoch 21/100
1000/1000 - 0s - loss: 0.3685
Epoch 22/100
1000/1000 - 0s - loss: 0.3781
Epoch 23/100
1000/1000 - 0s - loss: 0.38

## Extract the weights and bias

In [10]:
model.layers[0].get_weights()

[array([[ 1.908462],
        [-3.061198]], dtype=float32), array([4.973312], dtype=float32)]

In [11]:
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.908462],
       [-3.061198]], dtype=float32)

In [12]:
bias = model.layers[0].get_weights()[1]
bias

array([4.973312], dtype=float32)

## Extract the outputs (make predictions)

In [ ]:
model.predict_on_batch(training_data['inputs'])#.round(1)


In [ ]:
training_data['targets'].round(1)
type(training_data)

## Plotting the data

In [ ]:
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()

In [ ]:
deltas = model.predict_on_batch(training_data['inputs']) - training_data['targets']
loss = (deltas ** 2) / 2 / observations
print (loss)


