In [7]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Creating Tensor

In [9]:
# -----------------  SCALAR -----------------------------------
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
print(string, number, floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a String'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


Rank / Degree

In [11]:
# Scalar has 0 rank
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [12]:
rank1_tensor = tf.Variable(["Test","Ok","Tim"], tf.string)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
rank2_tensor = tf.Variable([["Test1","Ok1","Tim1"],["Test2","Ok2","Tim2"]], tf.string)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
rank3_tensor = tf.Variable([[["Test1","Ok1","Tim1"],["Test2","Ok2","Tim2"]], [["Test3","Ok3","Tim3"],["Test4","Ok4","Tim4"]]], tf.string)
tf.rank(rank3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

Shape : Tells the item in each dimension

In [19]:
number.shape

TensorShape([])

In [20]:
rank1_tensor.shape

TensorShape([3])

In [21]:
rank2_tensor.shape

TensorShape([2, 3])

In [22]:
rank3_tensor.shape

TensorShape([2, 2, 3])

Changing Shape : Reshape


In [24]:
tf1 = tf.ones([1,2,3])
tf1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [25]:
tf2 = tf.reshape(tf1,[2,3,1])
tf2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [26]:
tf3 = tf.reshape(tf1,[3,1,2])
tf3

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]], dtype=float32)>

In [28]:
tf4 = tf.reshape(tf1,[3, -1])   # -1 tells tensor to calculate the size of dimension in that  place : Reshapes to [3,2]
tf4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

#Type of Tensor:
### Variable        # Only variable is not immutable
### Constant
### Placeholder
### Sparsetensor 

In [29]:
tf5 = tf.ones([5,5,5])
tf5

<tf.Tensor: shape=(5, 5, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [31]:
tf6 = tf.reshape(tf5, [125])
tf6

<tf.Tensor: shape=(125,), dtype=float32, numpy=
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.], dtype=float32)>

In [32]:
tf7 = tf.reshape(tf5, [5,-1])
tf7

<tf.Tensor: shape=(5, 25), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>